# Generated by Django 4.2.3 on 2023-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('star_rating', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
